SERIAL_BAUDRATE = 115200
SERIAL_PORT = '/dev/ttyUSB0'

SERVICE_HOST = '127.0.0.1'
SERVICE_PORT = 8080

SERVICE_URI = 'tcp:%d' % SERVICE_PORT
WS_URI = 'ws://%s:%d' % (SERVICE_HOST, SERVICE_PORT)
WS_PATH = 'ws'

MQTT_BROKER_HOST = '192.168.0.22'
MQTT_BROKER_PORT = 1883
MQTT_BROKER_URI = 'tcp:%s:%d' % (MQTT_BROKER_HOST, MQTT_BROKER_PORT)
